package cn.test.model;

import java.io.Serializable;
import java.util.Date;

public class Dic implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DIC.DIC_ID
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    private Integer dicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DIC.BUSI_SCENE_CODE
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    private String busiSceneCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DIC.DIC_CODE
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    private String dicCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DIC.DIC_NAME
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    private String dicName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DIC.DISPLAY_ORDER
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    private Short displayOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DIC.CREATE_STAFF
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    private String createStaff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DIC.CREATE_TIME
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DIC.LAST_MODI_TIME
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    private Date lastModiTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DIC.STATUS
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYS_DIC
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_DIC
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public Dic(Integer dicId, String busiSceneCode, String dicCode, String dicName, Short displayOrder, String createStaff, Date createTime, Date lastModiTime, Short status) {
        this.dicId = dicId;
        this.busiSceneCode = busiSceneCode;
        this.dicCode = dicCode;
        this.dicName = dicName;
        this.displayOrder = displayOrder;
        this.createStaff = createStaff;
        this.createTime = createTime;
        this.lastModiTime = lastModiTime;
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_DIC
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public Dic() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DIC.DIC_ID
     *
     * @return the value of SYS_DIC.DIC_ID
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public Integer getDicId() {
        return dicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DIC.DIC_ID
     *
     * @param dicId the value for SYS_DIC.DIC_ID
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public void setDicId(Integer dicId) {
        this.dicId = dicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DIC.BUSI_SCENE_CODE
     *
     * @return the value of SYS_DIC.BUSI_SCENE_CODE
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public String getBusiSceneCode() {
        return busiSceneCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DIC.BUSI_SCENE_CODE
     *
     * @param busiSceneCode the value for SYS_DIC.BUSI_SCENE_CODE
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public void setBusiSceneCode(String busiSceneCode) {
        this.busiSceneCode = busiSceneCode == null ? null : busiSceneCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DIC.DIC_CODE
     *
     * @return the value of SYS_DIC.DIC_CODE
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public String getDicCode() {
        return dicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DIC.DIC_CODE
     *
     * @param dicCode the value for SYS_DIC.DIC_CODE
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public void setDicCode(String dicCode) {
        this.dicCode = dicCode == null ? null : dicCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DIC.DIC_NAME
     *
     * @return the value of SYS_DIC.DIC_NAME
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public String getDicName() {
        return dicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DIC.DIC_NAME
     *
     * @param dicName the value for SYS_DIC.DIC_NAME
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public void setDicName(String dicName) {
        this.dicName = dicName == null ? null : dicName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DIC.DISPLAY_ORDER
     *
     * @return the value of SYS_DIC.DISPLAY_ORDER
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public Short getDisplayOrder() {
        return displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DIC.DISPLAY_ORDER
     *
     * @param displayOrder the value for SYS_DIC.DISPLAY_ORDER
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public void setDisplayOrder(Short displayOrder) {
        this.displayOrder = displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DIC.CREATE_STAFF
     *
     * @return the value of SYS_DIC.CREATE_STAFF
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public String getCreateStaff() {
        return createStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DIC.CREATE_STAFF
     *
     * @param createStaff the value for SYS_DIC.CREATE_STAFF
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public void setCreateStaff(String createStaff) {
        this.createStaff = createStaff == null ? null : createStaff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DIC.CREATE_TIME
     *
     * @return the value of SYS_DIC.CREATE_TIME
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DIC.CREATE_TIME
     *
     * @param createTime the value for SYS_DIC.CREATE_TIME
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DIC.LAST_MODI_TIME
     *
     * @return the value of SYS_DIC.LAST_MODI_TIME
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public Date getLastModiTime() {
        return lastModiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DIC.LAST_MODI_TIME
     *
     * @param lastModiTime the value for SYS_DIC.LAST_MODI_TIME
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public void setLastModiTime(Date lastModiTime) {
        this.lastModiTime = lastModiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DIC.STATUS
     *
     * @return the value of SYS_DIC.STATUS
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DIC.STATUS
     *
     * @param status the value for SYS_DIC.STATUS
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public void setStatus(Short status) {
        this.status = status;
    }
}