package cn.test.model;

import java.io.Serializable;
import java.util.Date;

public class News implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_NEWS.NEWS_ID
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    private Long newsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_NEWS.TITLE
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_NEWS.PIC_PATH
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    private String picPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_NEWS.NEWS_TYPE
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    private Short newsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_NEWS.STATE
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    private Short state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_NEWS.CREATE_TIME
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_NEWS.CREATE_USER_NAME
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    private String createUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_NEWS.CREATE_USER_ID
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_NEWS.NEWS_CONTENT
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    private String newsContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BIZ_NEWS
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_NEWS
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public News(Long newsId, String title, String picPath, Short newsType, Short state, Date createTime, String createUserName, Long createUserId, String newsContent) {
        this.newsId = newsId;
        this.title = title;
        this.picPath = picPath;
        this.newsType = newsType;
        this.state = state;
        this.createTime = createTime;
        this.createUserName = createUserName;
        this.createUserId = createUserId;
        this.newsContent = newsContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_NEWS
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public News() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_NEWS.NEWS_ID
     *
     * @return the value of BIZ_NEWS.NEWS_ID
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public Long getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_NEWS.NEWS_ID
     *
     * @param newsId the value for BIZ_NEWS.NEWS_ID
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public void setNewsId(Long newsId) {
        this.newsId = newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_NEWS.TITLE
     *
     * @return the value of BIZ_NEWS.TITLE
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_NEWS.TITLE
     *
     * @param title the value for BIZ_NEWS.TITLE
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_NEWS.PIC_PATH
     *
     * @return the value of BIZ_NEWS.PIC_PATH
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public String getPicPath() {
        return picPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_NEWS.PIC_PATH
     *
     * @param picPath the value for BIZ_NEWS.PIC_PATH
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public void setPicPath(String picPath) {
        this.picPath = picPath == null ? null : picPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_NEWS.NEWS_TYPE
     *
     * @return the value of BIZ_NEWS.NEWS_TYPE
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public Short getNewsType() {
        return newsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_NEWS.NEWS_TYPE
     *
     * @param newsType the value for BIZ_NEWS.NEWS_TYPE
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public void setNewsType(Short newsType) {
        this.newsType = newsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_NEWS.STATE
     *
     * @return the value of BIZ_NEWS.STATE
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_NEWS.STATE
     *
     * @param state the value for BIZ_NEWS.STATE
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public void setState(Short state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_NEWS.CREATE_TIME
     *
     * @return the value of BIZ_NEWS.CREATE_TIME
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_NEWS.CREATE_TIME
     *
     * @param createTime the value for BIZ_NEWS.CREATE_TIME
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_NEWS.CREATE_USER_NAME
     *
     * @return the value of BIZ_NEWS.CREATE_USER_NAME
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_NEWS.CREATE_USER_NAME
     *
     * @param createUserName the value for BIZ_NEWS.CREATE_USER_NAME
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_NEWS.CREATE_USER_ID
     *
     * @return the value of BIZ_NEWS.CREATE_USER_ID
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_NEWS.CREATE_USER_ID
     *
     * @param createUserId the value for BIZ_NEWS.CREATE_USER_ID
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_NEWS.NEWS_CONTENT
     *
     * @return the value of BIZ_NEWS.NEWS_CONTENT
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public String getNewsContent() {
        return newsContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_NEWS.NEWS_CONTENT
     *
     * @param newsContent the value for BIZ_NEWS.NEWS_CONTENT
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public void setNewsContent(String newsContent) {
        this.newsContent = newsContent == null ? null : newsContent.trim();
    }
}