package cn.test.model;

import java.io.Serializable;
import java.util.Date;

public class Product implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_PRODUCT.PRODUCT_ID
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_PRODUCT.PRODUCT_NAME
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_PRODUCT.BIG_TYPE
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    private Integer bigType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_PRODUCT.SMALL_TYPE
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    private Integer smallType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_PRODUCT.PIC_PATH
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    private String picPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_PRODUCT.STATE
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    private Short state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_PRODUCT.CREATE_TIME
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_PRODUCT.CREATE_USER_NAME
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    private String createUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_PRODUCT.CREATE_USER_ID
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_PRODUCT.PRODUCT_CONTENT
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    private String productContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BIZ_PRODUCT
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_PRODUCT
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public Product(Long productId, String productName, Integer bigType, Integer smallType, String picPath, Short state, Date createTime, String createUserName, Long createUserId, String productContent) {
        this.productId = productId;
        this.productName = productName;
        this.bigType = bigType;
        this.smallType = smallType;
        this.picPath = picPath;
        this.state = state;
        this.createTime = createTime;
        this.createUserName = createUserName;
        this.createUserId = createUserId;
        this.productContent = productContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_PRODUCT
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public Product() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_PRODUCT.PRODUCT_ID
     *
     * @return the value of BIZ_PRODUCT.PRODUCT_ID
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_PRODUCT.PRODUCT_ID
     *
     * @param productId the value for BIZ_PRODUCT.PRODUCT_ID
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_PRODUCT.PRODUCT_NAME
     *
     * @return the value of BIZ_PRODUCT.PRODUCT_NAME
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_PRODUCT.PRODUCT_NAME
     *
     * @param productName the value for BIZ_PRODUCT.PRODUCT_NAME
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_PRODUCT.BIG_TYPE
     *
     * @return the value of BIZ_PRODUCT.BIG_TYPE
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public Integer getBigType() {
        return bigType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_PRODUCT.BIG_TYPE
     *
     * @param bigType the value for BIZ_PRODUCT.BIG_TYPE
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public void setBigType(Integer bigType) {
        this.bigType = bigType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_PRODUCT.SMALL_TYPE
     *
     * @return the value of BIZ_PRODUCT.SMALL_TYPE
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public Integer getSmallType() {
        return smallType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_PRODUCT.SMALL_TYPE
     *
     * @param smallType the value for BIZ_PRODUCT.SMALL_TYPE
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public void setSmallType(Integer smallType) {
        this.smallType = smallType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_PRODUCT.PIC_PATH
     *
     * @return the value of BIZ_PRODUCT.PIC_PATH
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public String getPicPath() {
        return picPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_PRODUCT.PIC_PATH
     *
     * @param picPath the value for BIZ_PRODUCT.PIC_PATH
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public void setPicPath(String picPath) {
        this.picPath = picPath == null ? null : picPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_PRODUCT.STATE
     *
     * @return the value of BIZ_PRODUCT.STATE
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_PRODUCT.STATE
     *
     * @param state the value for BIZ_PRODUCT.STATE
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public void setState(Short state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_PRODUCT.CREATE_TIME
     *
     * @return the value of BIZ_PRODUCT.CREATE_TIME
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_PRODUCT.CREATE_TIME
     *
     * @param createTime the value for BIZ_PRODUCT.CREATE_TIME
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_PRODUCT.CREATE_USER_NAME
     *
     * @return the value of BIZ_PRODUCT.CREATE_USER_NAME
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_PRODUCT.CREATE_USER_NAME
     *
     * @param createUserName the value for BIZ_PRODUCT.CREATE_USER_NAME
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_PRODUCT.CREATE_USER_ID
     *
     * @return the value of BIZ_PRODUCT.CREATE_USER_ID
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_PRODUCT.CREATE_USER_ID
     *
     * @param createUserId the value for BIZ_PRODUCT.CREATE_USER_ID
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_PRODUCT.PRODUCT_CONTENT
     *
     * @return the value of BIZ_PRODUCT.PRODUCT_CONTENT
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public String getProductContent() {
        return productContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_PRODUCT.PRODUCT_CONTENT
     *
     * @param productContent the value for BIZ_PRODUCT.PRODUCT_CONTENT
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    public void setProductContent(String productContent) {
        this.productContent = productContent == null ? null : productContent.trim();
    }
}