package cn.test.mapper.base;

import cn.test.model.News;

public interface NewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_NEWS
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    int deleteByPrimaryKey(Long newsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_NEWS
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    int insert(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_NEWS
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    int insertSelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_NEWS
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    News selectByPrimaryKey(Long newsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_NEWS
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    int updateByPrimaryKeySelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_NEWS
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_NEWS
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    int updateByPrimaryKey(News record);
}