package cn.test.mapper.base;

import cn.test.model.Product;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_PRODUCT
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    int deleteByPrimaryKey(Long productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_PRODUCT
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_PRODUCT
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_PRODUCT
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    Product selectByPrimaryKey(Long productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_PRODUCT
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_PRODUCT
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_PRODUCT
     *
     * @mbggenerated Tue Apr 12 14:01:08 CST 2016
     */
    int updateByPrimaryKey(Product record);
}